[CHORE]  CI 스크립트 작성
debate-timer/debate-timer-be pull request #21
Opened 2024-12-13 15:23 UTC by coli-geonwoo

# 🚩 연관 이슈
closed #20

# ⭐ CI Description
- event trigger: develop 브랜치에 PR이 발생(PR branch의 새로운 push도 포함)
1) test를 수행합니다.
2) Junit Test Report를 발행합니다.
3) Jacoco 라이브러리를 통해 테스트 커버리지를 검증합니다.

```yml
      - name: Report test Coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📝 Test Coverage Report
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          update-comment: true
          debug-mode: true
```

    - min-coverage-overall: 전체 코드 커버리지 기준
    - min-coverage-changed-files: 변경한 파일에 대한 테스트 커버리지
    - update-comment: 스크립트가 돌때마다 새로 생성하지 않고 PR 내에 comment를 업데이트
    - debug-mode: 오류 발생시 디버깅 모드로 돌리고 에러 내역을 콘솔에 출력

# 🗣️ 리뷰 요구사항 (선택)

2024-12-14 03:13 UTC, leegwichan approved these changes
/noti
PR을 통해 정상 작동 확인했습니다!
제안 사항 달아 두었으니 가능한 부분만 반영 부탁드릴께요!

2024-12-14 03:13 UTC, leegwichan commented on build.gradle
>  }
[제안] local에서 테스트할 때도 항상 `jacocoTestReport`가 실행될 것 같은데, 더 좋은 방안 없을까요? (특정 옵션을 주어야만 작동하게 한다거나 등등...)

2024-12-14 08:57 UTC, coli-geonwoo commented on build.gradle
>  }
TEST_REPORT 환경변수 옵션에 따라서 실행여부를 결정하도록 하였습니다. 
- local에서는 환경변수가 없어서 실행되지 않음
- Script 상에서는 env 설정을 통해

```yml
jacocoTestReport {
    dependsOn test
    reports {
        xml.required.set(true)
        csv.required.set(false)
        html.required.set(false)
    }

    //dto는 테스트 대상에서 제외
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    "com/debatetimer/**/dto/**"
            ])
        }))
    }

    **onlyIf {
        return System.getenv('TEST_REPORT') == 'true'
    }**
}
```

### CI script 에서 환경 변수 설정
```yaml
name: dev-ci

on:
  pull_request:
    branches:
      - develop

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      TEST_REPORT: true
```

2024-12-14 08:57 UTC, coli-geonwoo commented on .github/workflows/Backend_Dev_CI.yml
✅ 반영 완료

2024-12-14 08:58 UTC, coli-geonwoo commented
/noti

- gradle 캐싱 활용하도록 수정
- lombok & dto 클래스 테스트 되지 않도록 수정
- local에서는 test report 발행되지 않도록 수정

2024-12-15 03:19 UTC, unifolio0 requested changes
/noti
콜리 ci 스크립트에 관해서 궁금한 부분이 있어 RC 남겼어요~
확인 부탁드려요

2024-12-15 03:19 UTC, unifolio0 commented on .github/workflows/Dev_CI.yml
> +            ${{ runner.os }}-gradle-
gradle을 캐싱하는 부분 같은데 gitHub 공식문서에서는 actions의 활용을 권장하고 있습니다.
https://docs.github.com/ko/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle#caching-dependencies

2024-12-15 03:19 UTC, unifolio0 commented on .github/workflows/Dev_CI.yml
> +permissions: write-all
쓰기 권한이 너무 광범위 한 것 같아요. 필요한 권한만 주는 건 어떤가요?

2024-12-15 03:19 UTC, unifolio0 commented on .github/workflows/Dev_CI.yml
> +    timeout-minutes: 2
2분으로 설정한 기준이 궁금해요

2024-12-15 03:19 UTC, unifolio0 commented on .github/workflows/Dev_CI.yml
> +          debug-mode: true
이건 제가 잘 몰라서 질문드립니다.
지금 `Publish Test Results`와 `JUnit Report Action`는 `if: always()`를 통해 앞의 step이 실패해도 동작하게 하는 것 같은데 `Report test Coverage to PR`는 그런 조건이 없어도 앞의 step에서 실패해도 동작하나요? 
해당 부분이 테스트 결과를 PR에 코멘트로 올리는 부분 같은데 `if: always()`이게 없어도 작동하는 지 궁금해서 질문드립니다.

2024-12-15 08:28 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +          debug-mode: true
✅  [반영 완료]

if: always()추가해주었습니다.

이전에 실패한 스크립트 파일을 보니 실행이 되지 않네요! 디테일한 부분 리뷰남겨주어서 고마워요 비토! 역시 👍 
![image](https://github.com/user-attachments/assets/943eca2e-4026-43a2-a85d-9e346146a31e)

2024-12-15 08:28 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +    timeout-minutes: 2
도메인이 커진 오디 CI 스크립트가 1분 40초정도 소모되어 현재 프로젝트 규모에서 확장된 상황을 감안했을 때에도 2분이라는 기준이 이상치를 판단하기에 적정한 기준이라 생각했던 것 같아요.

2024-12-15 09:29 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +    timeout-minutes: 2
다시 보니 1분 40초가 아니라 2분 40초 정도였네요... 3분으로 늘려주었습니다. GPT도 gradle test까지 2분은 너무 짧다고 하네요 😓

2024-12-15 09:34 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +            ${{ runner.os }}-gradle-
✅ 반영 완료!

2024-12-15 09:34 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +permissions: write-all
**✅ 반영 완료**

```yml
permissions:
  contents: read
  checks: write
  pull-requests: write
```

2024-12-15 09:35 UTC, coli-geonwoo commented
/noti

@unifolio0 

리뷰 모두 반영하였고 의견도 남겼으니 천천히 살펴봐주세요~

2024-12-15 09:38 UTC, unifolio0 requested changes
/noti
리뷰 관련해서 다 확인했습니다!
근데 정말 사소한 궁금증 있어서 RC 남겨요~

2024-12-15 09:38 UTC, unifolio0 commented on .github/workflows/Dev_CI.yml
> +    branches:
이 조건은 왜 필요한가요?

2024-12-15 09:45 UTC, coli-geonwoo commented on .github/workflows/Dev_CI.yml
> +    branches:
permissions 관련해서 push하면서 실험해보다가 원상복구 해주었는데, local에서만 반영되고 push가 안되었어요 😓  복구해주었습니다!

2024-12-15 09:47 UTC, coli-geonwoo commented
/noti 

트리거 원상복구 반영하였습니다! (local에서 수정하고 복구된 부분이 push가 안되었었네요 😓 ) ㅎㅎ 꼼꼼한 비토와의 PR 벌써부터 기대되어요 💪

2024-12-15 09:51 UTC, unifolio0 approved these changes
/noti
깔끔하네요. merge도 바로 하겠습니다!

2024-12-15 09:52 UTC, merged