[TEST] BaseXXXTest 환경 세팅하기
debate-timer/debate-timer-be pull request #30
Opened 2024-12-16 09:04 UTC by unifolio0

# 🚩 연관 이슈
closed #23 

# 🗣️ 리뷰 요구사항 (선택)
추가로 넣어야 할 세팅 있으면 말해주세요~

2024-12-16 10:55 UTC, leegwichan approved these changes
/noti

일단 문제 없는 것 같네요~
나중에 개발하면서 추가해보도록 하죠

2024-12-17 06:26 UTC, coli-geonwoo requested changes
/noti

비토, 빠르게 작업해주어서 너무나 고마워요. 또, 상황 상 리뷰를 조금 늦게 남기게 되어 미안합니다 🙇  몇 가지 사소하지만 궁금한 부분에 질문 남겨서 답변만 듣고 approve 하도록 할게요!

2024-12-17 06:26 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/BaseRepositoryTest.java
> +public abstract class BaseRepositoryTest {
@DataJpaTest에는 내부에 @Transactional이 붙여져 있어서 DataBaseCleaner Extend가 필요하지 않을 것 같은데, 비토는 어떻게 생각하나요?

```java

@TypeExcludeFilters({DataJpaTypeExcludeFilter.class})
@Transactional
@AutoConfigureCache
@AutoConfigureDataJpa
@AutoConfigureTestDatabase
@AutoConfigureTestEntityManager
@ImportAutoConfiguration
public @interface DataJpaTest {

}

```

2024-12-17 06:26 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/BaseControllerTest.java
> +@ExtendWith(DataBaseCleaner.class)
질문)

이전 프로젝트에서는 조합으로 DataBaseCleaner를가지고 있고 @BeforeEach를 통해 cleanUp을 하도록 하였는데요.

ExtendWith으로 사용하면 무엇이 더 좋은지? 혹은 ExtendWith으로는 어떤 방식으로 사용하는지 궁금해요.

참고 ) 오디 BaseControllerTest 

```java
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public abstract class BaseControllerTest {

    @Autowired
    private DatabaseCleaner databaseCleaner;

    @BeforeEach
    void databaseCleanUp() {
        databaseCleaner.cleanUp();
    }

    @LocalServerPort
    private int port;

    @BeforeEach
    void setPort() {
        RestAssured.port = port;
    }
}
```

2024-12-17 06:26 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/DataBaseCleaner.java
> +public class DataBaseCleaner implements BeforeEachCallback {
아하 이렇게 사용하면 extend 된 곳에서 자동으로 beforeEach callback 함수로 등록이 되는 거군요... 👍 

배워갑니다.. 너무 좋네요

2024-12-17 06:26 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/DataBaseCleaner.java
> +    private List<String> findTableNames(EntityManager em) {
[제안]

지금도 좋은데 이 부분 코드 상으로 관리해주는 건 어떨까요?
unchecked warning suppress가 없어진다는 점에서 매력적인 것 같아요.

코드 상에서 @Entity가 붙어있는 클래스의 엔티티 이름을 추적해서 tableName을 가져오는 코드입니다!

```java
    List<String findTablesNames() {
        return entityManager.getMetamodel()
                .getEntities().stream()
                .filter(entityType -> entityType.getJavaType().getAnnotation(Entity.class) != null)
                .map(entityType -> CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, entityType.getName())) // 이름을 카멜 케이스 > 스네이크 & 소문자로 변경
                .toList();
    }
```

2024-12-17 06:29 UTC, unifolio0 commented
/noti
@unifolio0

2024-12-17 06:33 UTC, unifolio0 commented on src/test/java/com/debatetimer/BaseRepositoryTest.java
> +public abstract class BaseRepositoryTest {
오 몰랐네요, 덕분에 배워갑니다~

2024-12-17 06:49 UTC, unifolio0 commented on src/test/java/com/debatetimer/DataBaseCleaner.java
> +    private List<String> findTableNames(EntityManager em) {
`unchecked warning suppress`가 없어지는 게 매력적이라고 생각한 이유가 궁금해요!

지금 코드는 타입 안정성 부분에선 콜리의 제안보다 위험하겠지만 해당 문제가 발생할 확률은 매우 낮다고 생각해요.
또 지금 코드에선 만약 벤더사가 변경되면 SQL이 변경될 확률도 있죠.

콜리 코드에서는 지금 스네이크 케이스로 변경하는 부분이 있는데 만약 다른 사람이 table이름을 지정해줄 때 실수가 생기면 문제가 발생할 수 있겠네요.
그리고 가능성은 매우 낮지만 나중에 JPA말고 다른 방식으로 DB와 연결하게 되면 그 테이블만 따로 관리를 해줄 필요가 있고요.

제가 코드를 비교하면서 생각한 부분들인데 각각에 대한 콜리의 의견이 궁금합니다!

2024-12-17 11:40 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/DataBaseCleaner.java
> +    private List<String> findTableNames(EntityManager em) {
> unchecked warning suppress가 없어지는 게 매력적이라고 생각한 이유

개발자가 예외 발생의 사이드 이펙트가 없음을 인식한 상태로 unchecked suppress를 명시하는 코드보다 코드 상에서 타입 안전성을 확보하는 것이 좋다고 생각했기 때문이에요. 다만 벤더사 변경, Table 이름 지정과 관련한 실수에 있어서 깊은 고민을 해보지는 않았어요.

그런데 비토 이야기를 들으며 설득이 되었어요.

제가 이야기한 상황에 대한 확률은 다음과 같아요.
- 타입안정성이 발생할 확률
- 예외 발생 상황에 대해 SuppressWarning보다 코드로 억제하는 것이 

그리고, 비토가 근거로 이야기한 상황의 확률은 다음과 같아요.
- SQL 벤더 변경 시
- JPA 미사용 시
- table 이름 지정 실수 시

우선 SQL 벤더 변경과 JPA 미사용의 확률은 극히 낮다고 생각하고, table 이름 지정 실수 시 발생하는 에러는 오히려 table 이름에 대한 컨벤션에 대한 검사 효과를 볼 수 있다고도 생각했어요. 또한, 해당 코드에서 Table이름을 변경하지 않고 그대로 가져오는 식으로 작성되어도 괜찮다고 생각해요.

그러나, `성능면에서는 그래도 db 통신이 리플랙션보다 빠를 것 같긴한데` 이 부분이 조금 와닿았던 것 같아요. 현재는 리플렉션으로 모든 클래스 로딩 > Entity 애너테이션 검사 > Table 이름 추출 식으로 런타임에 table name들을 추출하는데 확실히 DB 관점에서는 DB 쿼리 하나로 clean 작업을 하는게 효율적이고, 작업의 추상화 준위에도 맞다는 생각이 확들었어요.

나중에 Entity가 여러개 생기면 한번 clean 작업을 변경해서 시간이 얼마나 걸리는지 측정해보아도 좋을 것 같아요~

2024-12-17 11:42 UTC, coli-geonwoo approved these changes
/noti

비토의 리뷰는 항상 제게 생각할 거리들을 던져주네요. 저도 답변드렸어요. 결론적으로는 비토 생각에 설득되었으나, 제 생각들을 비토가 한번은 읽어주었으면 좋겠다는 마음으로 merge는 비토에게 맡겨둘게요!

항상 좋은 인사이트 주어서 고마워요 👏

2024-12-18 13:24 UTC, merged

2024-12-18 17:11 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/DataBaseCleaner.java
> +    private List<String> findTableNames(EntityManager em) {
` 리플렉션에 대한 이해가 선행되야 이해가 가능하지만 지금 코드는 그보다 백그라운드가 적어도 이해가 가능할 것 같아요!`

음... 그러네요. 이 부분에서도 비토가 이야기한 방안이 좋을 수 있을 것 같아요. 답변 남겨주어 감사합니다 😄