[FEAT] Entity 및 DB 세팅
debate-timer/debate-timer-be pull request #32
Opened 2024-12-19 12:20 UTC by unifolio0

# 🚩 연관 이슈
closed #31 

# 🗣️ 리뷰 요구사항 (선택)
추가로 더할게 있는 지 잘 모르겠네요. 만약 제가 놓친게 있으면 말해주세요!

2024-12-20 02:30 UTC, leegwichan requested changes
/noti
비토가 놓친 부분이 있는 것 같아 코멘트 남겼습니다! 반영하거나 댓글 남겨주세요!

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/Member.java
> +    @Column(name = "nickname")
[질문] 모든 컬럼에 name을 명시한 이유가 있나요?
[제안] `@JoinColumn`을 사용하는 부분을 제외하고는 name을 명시하지 않는 건 어떨까요?

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    @NotNull
[필수] 빈 공백 한 칸 줄여주세요

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
[질문] "특정 타입에 특정 Stance만 허용"된다는 로직은 콜리가 구현하는거죠?

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
[질문] `name` 값은 서버에서 가지고 있지 않아도 되는 것 아닌가요?

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +import jakarta.persistence.*;
[필수] import에서 와일드카드 빼주세요

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/.gitkeep
👍

2024-12-20 02:30 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/Stance.java
> +    NEUTRAL("중립"),
[질문] `name` 값은 서버에서 가지고 있지 않아도 되는 것 아닌가요?

2024-12-20 11:30 UTC, coli-geonwoo requested changes
/noti

@leegwichan  @unifolio0 

비토! 빠르게 작업해주어서 감사합니다 🙇  다만, 기능 명세서에 있는 도메인 규칙이 같이 검증되었으면 좋겠어요. 추가로 Embedded에 대해 어떻게 생각하는지, 커찬/비토의 의견이 궁금하네요!

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/Member.java
> +    @Column(name = "nickname")
[의견]

저도 필드명과 Db column 이름이 일치하지 않는 경우를 제외하고는 name 옵션을 붙이지는 않았던 것 같아요.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/Member.java
> +    private String nickname;
nickname 길이가 1자 이상 10자 이하여야 한다. / 영문, 한글만 포함한다. 에 대한 도메인 검증이 있으면 좋겠어요.

+) Embedded 타입에 대한 커찬과 비토의 의견이 궁금합니다.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +    private String name;
TableName의 경우에도 기능 명세서에 있는 도메인 검증이 필요해보입니다.
- 1자 이상 20자 미만
- 영문/ 한글만 허용

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +    private int duration;
[제안]
양수 범위에 대한 검증은 어떨까요? , 필요하지 않다 생각하거나 과한 검증이라 생각하면 의견 남겨주어도 좋아요.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    @NotNull
마찬가지로 양수 범위 검증에 대해 어떻게 생각하는지 궁금합니다.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    private int speaker;
speaker는 Nullable하기 때문에 Integer나 Long으로 Wrapper 타입 선언이 필요해보입니다.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +public enum ParliamentaryType {
[제안]
ParliamentaryType은 의회식 유형으로 해석되어서 토론 발언 시간 하나에 대한 타입으로 바라보는 건 어떨까요? 다른 유형의 토론에서도 입론, 반론, 최종 발언등은 활용가능할 것 같아요.

혹은 BoxType과 같은 네이밍은 어떨까 생각합니다.

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    OPENING("입론"),
입론, 반론 등의 문자열을 필드로 가지고 있는 이유는 무엇인가요? 뷰 로직 상에서 쓰이는 부분이 없는 것 같아 여쭙습니다!

2024-12-20 11:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
> [질문] "특정 타입에 특정 Stance만 허용"된다는 로직은 콜리가 구현하는거죠?

네. List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.

2024-12-22 02:58 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/Member.java
> +    @Column(name = "nickname")
개인적으로 명시하는 것을 선호하지만 그리 중요하지 않은 내용인 것 같아 제거하겠습니다

2024-12-22 02:58 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    @NotNull
반영했습니다

2024-12-22 03:03 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +import jakarta.persistence.*;
인텔리제이 설정 문제였네요. 수정했습니다!

2024-12-22 03:04 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    private int speaker;
Integer로 수정했습니다!

2024-12-22 03:11 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    OPENING("입론"),
개인적으로 이 정도의 뷰는 백엔드에서도 어느 정도 알고 있어야 된다고 생각하는데 없는 걸 선호하는 것 같아 그리 중요한 내용이 아니기에 제거했습니다!

> 뷰 로직 상에서 쓰이는 부분이 없는 것 같아 여쭙습니다!

이 부분은 저희가 아직 뷰를 구현안해서 그렇지 나중에 프론트에 정보를 전송할 때 타입을 전송하지 않나요?

2024-12-22 03:11 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/Stance.java
> +    NEUTRAL("중립"),
https://github.com/debate-timer/debate-timer-be/pull/32#discussion_r1894748478

제거했습니다!

2024-12-22 03:12 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
> [질문] name 값은 서버에서 가지고 있지 않아도 되는 것 아닌가요?

https://github.com/debate-timer/debate-timer-be/pull/32#discussion_r1894748478

제거했습니다!

2024-12-22 03:14 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +public enum ParliamentaryType {
수정했습니다!

2024-12-22 03:16 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
>[질문] "특정 타입에 특정 Stance만 허용"된다는 로직은 콜리가 구현하는거죠?
네. List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.

List로 필요한 부분만 가지고 있는 것보단 클래스단에서 구분하는게 성능면에서나 코드 파악 면에서 더 좋을 것 같다고 판단하는데 어짜피 중복되는 부분도 많고 가짓수도 많지 않아서 성능도 크게 차이 안 날 것 같아 공통 타입으로 놔두겠습니다!

2024-12-22 03:21 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTimeBox.java
> +    @NotNull
수정했습니다!

2024-12-22 03:21 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +    private int duration;
수정했습니다!

2024-12-22 03:53 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +    private String name;
수정했습니다!

2024-12-22 03:53 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/Member.java
> +    private String nickname;
수정했습니다!

2024-12-22 03:54 UTC, unifolio0 commented
/noti
@leegwichan @coli-geonwoo 
리뷰 반영 끝났습니다!

> +) Embedded 타입에 대한 커찬과 비토의 의견이 궁금합니다.

저는 별로 안 좋아합니다! 있다가 5시에 회의할 때 이 부분도 회의하면 좋을 것 같아요.

2024-12-22 08:43 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
저도 이 부분 고민이 되기는 해요. 작전시간만 특수한 케이스로 보고 서비스 클래스에서 중립인지 검증할지, 혹은 각 BoxType이 허용가능한 Stance를 List 필드로 가지고 있게 할지..

비토랑 커찬 생각도 궁금하네요

2024-12-22 08:52 UTC, coli-geonwoo approved these changes
/noti

비토, 초반 세팅 작업이 팀원간의 의견차로 많이 부담스러웠을 텐데 의견 존중해주어서 고마워요. 몇가지 사소한 제안남겼으나 지금으로도 충분해보여서 approve 합니다!

2024-12-22 08:52 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +        if (duration <= 0) {
**[사소한 제안]**
서로의 스타일 차이라 생각하는데 duration과 name 검증이 한 곳에서 이루어지기보다 나누는 편이에요. 다만 검증 규모가 크지 않아서 지금도 괜찮아 보여요.

2024-12-22 08:52 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/Member.java
> +            throw new IllegalArgumentException("닉네임은 1자 이상 10자 이하여야 합니다");
// TODO
- 커스텀 에러객체로 바꾸어놓을게요.

2024-12-22 08:52 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/Stance.java
> +public enum Stance {
👍

2024-12-22 08:52 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/domain/MemberTest.java
> +        void 닉네임은_1자_이상_20자_이하여야_한다(int length) {
10자 이하여야 한다는 점에서 테스트명 수정이 필요해보입니다! 추가적으로 @NullAndEmptySource를 같이 붙여주면 empty  및 null 검증도 함께 할 수 있을 것 같습니당

```suggestion
        @ParameterizedTest
        @NullAndEmptySource
        @ValueSource(ints = {0, 11})
        void 닉네임은_1자_이상_10자_이하여야_한다(int length) {
```

2024-12-22 08:56 UTC, unifolio0 commented
/noti
@debate-timer/backend 
지금 추가로 상수화 적용했는데 개인적으로 상수를 public으로 여는 걸 딱히 꺼려하지 않습니다.
그래서 이 부분 컨벤션이 없는 것 같아 제 방식으로 public으로 열었는데 어떻게 생각하시는 지 궁금합니다.

https://github.com/debate-timer/debate-timer-be/pull/32/files/559354f5ea4512f41d087aae110aacdb5fd97cc6..4694c9f26f9146cf8539b67c04c5245b231722cd

2024-12-22 09:06 UTC, coli-geonwoo reviewed
/noti

저는 개인적으로
1) 리팩터링 내성이 강해짐
2) 테스트 동기화
3) 사용범위가 test로 한정되므로 OCP를 심각하게 훼손 x

이 점에서 괜찮은 것 같아요.

다만, 다른 클래스에서 무의식적으로 활용가능 or test를 위한 프로덕션 코드 변경이란 점에서 반박의 여지가 있을 것 같아요. 커찬의 생각이 궁금하네요.

결론적으로 저는 괜찮다고 생각합니다 👏

2024-12-22 09:11 UTC, unifolio0 commented
/noti
>다만, 다른 클래스에서 무의식적으로 활용가능 or test를 위한 프로덕션 코드 변경이란 점에서 반박의 여지가 있을 것 같아요. 커찬의 생각이 궁금하네요.

이 부분에 언급할 것이 있어 추가로 적습니다.
저는 test를 위해 프로덕션 코드가 바뀌는 것을 어느 정도까지는 부정적으로 여기지 않습니다.
그 기준은
1. 지금 코드 처럼 상수를 public으로 연다.
2. 테스트용 생성자를 만든다.

위의 2개는 오히려 적극적으로 사용하는 편입니다.

물론 다른 부분은 저도 반대합니다.

2024-12-22 14:42 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/Member.java
> +            throw new IllegalArgumentException("닉네임은 1자 이상 10자 이하여야 합니다");
이 부분 주석으로 남긴다 했었는데 깜빡했네요😅

2024-12-22 14:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
> +        if (duration <= 0) {
나누는 것에 대해선 저도 동의합니다! 다만 제가 나누는 기준은 검증 로직이 2개 이상인 필드가 2개 이상있을때 나누는 편입니다!

2024-12-23 00:04 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
/noti @unifolio0 

> 콜리 : List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.
비토 : List로 필요한 부분만 가지고 있는 것보단 클래스단에서 구분하는게 성능면에서나 코드 파악 면에서 더 좋을 것 같다고 판단하는데

 '클래스단에서 구분'하는 것이 성능이나 코드 파악 면에서 더 좋은 것 같아요. 하지만 `코트 파악이 좋다 -> 한 클래스 내 판단 로직을 모아놓는다 -> 한 클래스가 많은 역할을 한다 -> 나중에 기능이 추가되었을 경우 역할이 많아져서 이해하기 어려울 수 있다.` 이런 식으로 추후 코드가 복잡해질 염려가 있어 보이네요.
 물론 지금 생각했을 때는 그렇게 복잡한 로직이 없어 괜찮아 보이지만, 지금처럼 여유있을 때 `BoxType`에 역할을 두어서 로직을 분리하는 것도 좋은 방법이라 생각합니다!

2024-12-23 00:07 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryType.java
> +    ;
/noti @coli-geonwoo 

> 콜리 : List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.

이거 Set으로 하는게 O(1)으로 접근할 것 같아서 아주 사~알짝 더 효율적일 것 같아요

2024-12-23 00:08 UTC, leegwichan commented
/noti @unifolio0 

> 콜리 : List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.
비토 : List로 필요한 부분만 가지고 있는 것보단 클래스단에서 구분하는게 성능면에서나 코드 파악 면에서 더 좋을 것 같다고 판단하는데

 '클래스단에서 구분'하는 것이 성능이나 코드 파악 면에서 더 좋은 것 같아요. 하지만 `코트 파악이 좋다 -> 한 클래스 내 판단 로직을 모아놓는다 -> 한 클래스가 많은 역할을 한다 -> 나중에 기능이 추가되었을 경우 역할이 많아져서 이해하기 어려울 수 있다.` 이런 식으로 추후 코드가 복잡해질 염려가 있어 보이네요.
 물론 지금 생각했을 때는 그렇게 복잡한 로직이 없어 괜찮아 보이지만, 지금처럼 여유있을 때 `BoxType`에 역할을 두어서 로직을 분리하는 것도 좋은 방법이라 생각합니다!

2024-12-23 00:09 UTC, leegwichan commented
/noti @coli-geonwoo 

> 콜리 : List로 가능한 타입 유형을 Enum Type이 필드로 가지고 있게 하려고 해요.

이거 Set으로 하는게 O(1)으로 접근할 것 같아서 아주 사~알짝 더 효율적일 것 같아요

2024-12-23 00:22 UTC, leegwichan approved these changes
/noti @unifolio0 
Approve 날려드리나, 요청 사항 반영 부탁드립니다!

2024-12-23 00:22 UTC, leegwichan commented on src/test/java/com/debatetimer/domain/MemberTest.java
> +        }
나 이거 싫어하는 거 알면서... ^^;;
흠...... 나중에 추가로 이야기해 봅시다. 일단 가죠

2024-12-23 00:22 UTC, leegwichan commented on src/test/java/com/debatetimer/domain/MemberTest.java
> +                    .hasMessage(String.format("닉네임은 1자 이상 %d자 이하여야 합니다", Member.NICKNAME_MAX_LENGTH));
[제안] 자바 13부터 추가된 `formatted()`를 사용해보시는 건 어떨까요?

```suggestion
                    .hasMessage("닉네임은 1자 이상 %d자 이하여야 합니다".formatted(Member.NICKNAME_MAX_LENGTH), Member.NICKNAME_MAX_LENGTH));
```

2024-12-23 00:22 UTC, leegwichan commented on src/main/java/com/debatetimer/domain/ParliamentaryDebate/ParliamentaryTable.java
[필수] 패키지 이름 컨벤션!

> 5.2.1 Package names
Package names use only lowercase letters and digits (no underscores). Consecutive words are simply concatenated together. For example, `com.example.deepspace`, not `com.example.deepSpace` or `com.example.deep_space`.

2024-12-23 04:48 UTC, merged