[FEAT] TimeBox CRUD 구현
debate-timer/debate-timer-be pull request #38
Opened 2024-12-27 23:39 UTC by coli-geonwoo

# 🚩 연관 이슈
closed #24 

# 참고사항
- deleteAllInBatch
    - N+1 문제 방지를 위해 deleteAllInBatch를 사용했습니다.
    - batch 쿼리는 영속성 컨텍스트와 동기화되지 않고 **바로 DB에 쿼리를 날리는 구조라 entityManager.clear()를 통해 영속성 컨텍스트를 한번 초기**화해주었습니다. 그렇지 않을 경우 컨텍스트 내에는 삭제된 엔티티가 존재하여 DB에러가 발생합니다.

# 🗣️ 리뷰 요구사항 (선택)
- ParliamentaryTableCreateRequest / ParliamentaryTableResponse에서 dto >domain을 위해 책임이 과하게 넘어간 감이 있어요. 해당 로직을 service 단에서 수행해주어야 하는지, 혹은 지금 구조도 괜찮은지 궁금합니다.

2024-12-29 02:01 UTC, leegwichan requested changes
/noti @coli-geonwoo 콜리가 열심히 작성한 코드 잘 봤어요~
하지만 여러 부분에서 고민해 부분이 많은 것 같아요.
코멘트 15개 달았으니, 반영 or 추가 코멘트 부탁드릴께요

그리고 비토도 제꺼 리뷰 읽어보고 마음에 안드는 부분 있으면 코멘트 달아줘요.

2024-12-29 02:03 UTC, leegwichan commented
> ParliamentaryTableCreateRequest / ParliamentaryTableResponse에서 dto >domain을 위해 책임이 과하게 넘어간 감이 있어요. 해당 로직을 service 단에서 수행해주어야 하는지, 혹은 지금 구조도 괜찮은지 궁금합니다.

대충 스윽 읽어봤는데, 크게 문제될 부분은 없는 것 같아요. (이상 서비스 레이어가 무거워지면 병에 걸리는 사람 올림)

2024-12-29 07:27 UTC, unifolio0 requested changes
/noti
아무래도 이번 pr은 꽤 오래 걸릴 것 같네요. rc남겼어요. 확인해주세요~

2024-12-29 07:27 UTC, unifolio0 commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +                .orElseThrow(() -> new DTClientErrorException(ClientErrorCode.MEMBER_TABLE_NOT_FOUND));
혹시 tableId는 같은데 memberId가 다른 경우가 있나요? 아니면 다른 유저의 테이블을 조회하지 못하는 검증 기능을 의도한 건가요? 그러면 해당 tableId가 없는 경우와 다른 유저의 테이블을 조회하는 경우를 똑같이 처리하는 이유가 궁금해요!

2024-12-29 07:27 UTC, unifolio0 commented on src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
> +            ParliamentaryTableCreateRequest renewTableRequest =  dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
```suggestion
            ParliamentaryTableCreateRequest renewTableRequest = dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
```

2024-12-29 07:27 UTC, unifolio0 commented on src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
> +                    .hasMessage("타임박스 유형과 일치하지 않는 입장입니다.");
이왕에 Enum을 만든거 `getMessage`를 사용해서 메세지 검증해주세요.

2024-12-29 07:27 UTC, unifolio0 commented on src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
> +    }
순서를 지정하는 것이 dto에 있다는 게 조금 거슬리긴 하지만 마땅한 방법이 안 떠오르네요. 방법이 없으면 어쩔 수 없지만 한번 고민해보면 좋을 것 같아요

2024-12-29 07:27 UTC, unifolio0 commented on src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
> +        }
`ParliamentaryTableRepositoryTest`의 `특정_회원의_테이블만_조회한다` 테스트와는 달리 해당 테이블에 속하지 않은 `ParliamentaryTimeBox`는 만들지 않은 이유가 궁금해요

2024-12-29 07:27 UTC, unifolio0 commented on src/test/java/com/debatetimer/fixture/FixtureGenerator.java
> +public class FixtureGenerator {
저는 `FixtureGenerator`와 `DtoGenerator` 같은 클래스에 대해 그리 반기지는 않지만 어느 정도 필요성은 이해하는 입장이긴 합니다. 콜리가 TextFixture를 상수로 사용하는 것이 아닌 이렇게 메소드로 도입한 이유가 궁금하네요.

2024-12-29 19:52 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/argumentresolver/AuthMemberArgumentResolver.java
**✅ 반영완료**

`config 패키지`로 이동해주었습니다.

2024-12-29 19:53 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    @ResponseStatus(HttpStatus.OK)
- ResponseStatus의 기본값이 OK인지 몰랐어요.
- 저도 명시하는 편이 좋다고 생각합니다. Status를 사용한다는 것에 의의를 두기보다, 어떤 값을 반환하는지 코드상에서 읽히는게 중요하다고 생각해요

2024-12-29 19:56 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/auth/AuthMember.java
**✅  반영완료**

아직 패키지 구조를 결정하는데 개인적인 어려움이 있는데 고민하던 부분을 잘 집어주었네요 커찬

**domain.auth > controller.auth로 패키지를 이동**하여주었습니다. 추후 controller auth 패키지가 확장될 여지가 많다고 생각해 이런 구조가 합리적이라 생각했어요.

2024-12-29 19:57 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTable.java
> +import java.util.Objects;
✅  반영완료

2024-12-29 20:04 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        return new ParliamentaryTableResponse(existingTable, savedTimeBoxes);
**[질문 ✋ ]**

한 문단이 하나의 흐름으로 읽히길 의도한 부분이 있습니다.
1) 기존 table을 renewedTable로 update함
2) 기존 timeBoxes들을 찾아와서 삭제함
3) 새로운 timeboxes들을 저장함

2-3번 흐름을 timeBoxes 갱신이라는 맥락으로 하나로 읽어도 좋다고 생각한다면, 또 줄바꿈을 줄여도 맥락이 잘 읽히는 편이라면 반영토록 하겠습니다.

2024-12-29 20:05 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
> +        List<TimeBoxResponse> table
**✅  반영 완료**
명칭이 table이다보니 헷갈렸나봐요! 반영했습니다.

2024-12-29 20:09 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
> +                    .extract().as(ParliamentaryTableResponse.class);
**✅  반영 완료**

와우... 커찬에게 RestAssured 관련해서 많이 배워가네요...😮

2024-12-29 20:14 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +    }
✅  반영 완료

 `findTableTimeBoxes` 라는 메서드명이 괜찮은지 한번 물어보고 싶네요!

```java

default ParliamentaryTimeBoxes findTableTimeBoxes(ParliamentaryTable table) {
        List<ParliamentaryTimeBox> timeBoxes = findAllByParliamentaryTable(table);
        return new ParliamentaryTimeBoxes(timeBoxes);
}

```

2024-12-29 20:16 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +    }
✅ 반영 완료

커찬은 서비스 계층을 thin하게 유지하는 걸 좋아하는 군요~ 저도 그래요 ㅎㅎ

2024-12-29 20:29 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/argumentresolver/AuthMemberArgumentResolver.java
> +            return memberRepository.getById(memberId);
아닙니다. 다만 getById에서 반환하는 에러가 IllegalArgumentException이 아닌 DTClientException이어야 한다고 생각해요. 앞선 PR에서는 커스텀 에러객체를 반환하지 않았으나, 현재는 있는 상태이니 ClientErrorCode.MEMBER_NOT_FOUND를 가진 DTClientErrorException을 반환하도록 수정하는 것은 어떻게 생각하나요?

2024-12-29 20:30 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
> +
[질문 ✋ ]
시간이 양수라는 것이 비즈니스 규칙이라고 생각한 이유가 무엇인가요?
도메인 측면에서도 검증하고 DTO에서도 간단한 validation 들은 검증해줄 수 있다고 생각했습니다!

2024-12-29 20:31 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
**✅  반영 완료**

그렇네요! 반영해주었습니다~

2024-12-29 20:33 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/request/ParliamentaryTableCreateRequest.java
> +    }
저도 정확히 같은 부분이 굉장히 거슬렸어요. 특히 get(i) / i+1로 sequence를 정하는 부분이 하드코딩 적인 느낌도 나서 잘 읽힌다는 생각이 들었던 것 같아요.. 대안이 있으면 적극적으로 제안해주시면 반영해보겠습니다!

2024-12-29 20:34 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
> +                    .hasMessage("타임박스 유형과 일치하지 않는 입장입니다.");
✅ 반영 완료

그런 방법이!! 반영해주었습니다. 그러네요.. Enum을 더 잘 활용해봐야겠어요.

2024-12-29 20:36 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
> +                    .hasMessage("타임박스 유형과 일치하지 않는 입장입니다.");
아직 도메인 검증에 있어서는 Table,  Member와 마찬가지로 IlegalArgumentException으로 통일해놓은 상태에요. 후에 이슈를 하나 더 파서 IllegalArgumentException을 터트리고 있는 Member, Table 등을 커스텀 에러 객체로 한번에 통일할까 생각중인데 어떠신가요?

따라서, 아직 해당 에러코드를 Enum으로 선언해주지 않은 상태입니다.

2024-12-29 20:38 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
> +            ParliamentaryTableCreateRequest renewTableRequest =  dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
✅ 반영 완료

역시 꼼꼼하네요 비토! 반영해주었습니다 😄

2024-12-29 20:42 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +                .orElseThrow(() -> new DTClientErrorException(ClientErrorCode.MEMBER_TABLE_NOT_FOUND));
의도는 다른 유저의 테이블을 조회하지 못하도록 검증하는 것입니다.

비토의 말대로 좋은 코드를 위해서는 table 있는지 확인 -> member와 같은지 검증

이 과정이 반복되어야 하는데 CRUD 모든 코드에서 해당 검증이 코드상으로 필요했어요. 그래서 repository에서 하나의 쿼리로 의도한 table을 가져오는 것을 의도했습니다.

비토는 테이블이 없는 경우와, member소유의 테이블이 아닌 경우가 명백히 다르기 때문에 table을 가져오고 주인인지 검증하는 코드가 더 괜찮다고 생각하시나요?

2024-12-29 20:48 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/repository/parliamentary/ParliamentaryTimeBoxRepositoryTest.java
> +        }
**✅ 반영 료**

너무 화이트박스로 생각했나봐요. 특정 tableId를 기반으로 날아가는 timeBox들이 잘 추출되는지만 검증하면되리라 생각했어요. 더 엄밀하게 검증해주었습니다.

```java
@Test
        void 특정_테이블의_타임박스를_모두_조회한다() {
            Member chan = fixtureGenerator.generateMember("커찬");
            Member bito = fixtureGenerator.generateMember("비토");
            ParliamentaryTable chanTable = fixtureGenerator.generateParliamentaryTable(chan);
            ParliamentaryTable bitoTable = fixtureGenerator.generateParliamentaryTable(bito);
            ParliamentaryTimeBox chanBox1 = fixtureGenerator.generateParliamentaryTimeBox(chanTable, 1);
            ParliamentaryTimeBox chanBox2 = fixtureGenerator.generateParliamentaryTimeBox(chanTable, 2);
            ParliamentaryTimeBox bitoBox1 = fixtureGenerator.generateParliamentaryTimeBox(bitoTable, 2);
            ParliamentaryTimeBox bitoBox2 = fixtureGenerator.generateParliamentaryTimeBox(bitoTable, 2);

            List<ParliamentaryTimeBox> foundBoxes = parliamentaryTimeBoxRepository.findAllByParliamentaryTable(chanTable);

            assertThat(foundBoxes).containsExactly(chanBox1, chanBox2);
        }

```

2024-12-29 20:51 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
> +    }
1) 정팩매가 필요한 이유를 찾지 못했습니다.
2) 정팩매 사용을 허용한 것이지, 레코드에서 권장하는 식의 합의는 아니었던 걸로 기억했어요.
3) from, of가 의미를 담지 못하리라 생각했습니다.
4) 일전에 구현된 Dto 내의 dto to domain이 this로 구현되어 있어 일관성을 맞추고자 했습니다.

커찬/비토의 생각은 어떠신가요? 레코드에서 정팩메도 크게 불호는 아니에요.

2024-12-29 20:57 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBox.java
> +public class ParliamentaryTimeBox implements Comparable<ParliamentaryTimeBox> {
✅ 반영 완료

역시 객체지향 장인다운 예리한 포인트네요 커찬! 특히 Table이 다른 TimeBox들 간에는 비교대상이 아니라는 점이 굉장히 와닿았어요. Comparable과 Comparator의 차이를 체감하게 되는 순간이네요.

2024-12-29 21:02 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/request/TableInfoCreateRequest.java
> +        String type,
**✅  반영 완료**

그러네요?? API 문서 그대로 반영하다보니 토론 유형이 필요없다는 걸 눈치채지 못했어요. 반영해주었습니다.

2024-12-29 21:10 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/fixture/DtoGenerator.java
1) 맞아요. 그때는 FixtureGenerator를 각 도메인별로 나누어 사용할 것 같아요. ex) `MemberGenerator, ParliamentaryTableGenerator etc..`

2) 정확히 같은 이유 때문에 DTO Generator를 사용합니다
- DTO가 변경되면 test 코드가 아닌 generate 로직만 수정해주면 되기 때문에 상대적으로 테스트 코드 수정량이 적었어요.
- 테스트 코드에서 더 필요한 부분에 집중할 수 있었어요. 현재 우리 도메인은 DTO가 무거워 하나를 생성하기까지 굉장히 다양한 인자를 넘겨주어야 해요. 그러나, DToGenerator를 통해 필요한 인자값에만 집중해 테스트 흐름을 더 잘 이해할 수 있다고 생각했어요.

2024-12-29 21:14 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/fixture/FixtureGenerator.java
정확히 이 이유 때문에 FixtureMonkey를 사용했는데요. 이번에는 아마 도메인별로 FixtureGenerator를 분리할 것 같아요. MemberGenerator, TableGenerator처럼요.

2024-12-29 21:19 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
프론트 로직에 의존적인 API 설계보다는 save와 update 이후의 결과값을 반환하는게 일반적인 API 설계라고 생각했기 때문이에요.

첫째로, 실제 API 동작 결과를 확인할 수 있다는 점에서 테스트에 용이한 메서드라 생각했고,
둘째로, update와 save의 결과를 활용하는 것은 클라이언트 측의 선택이라 생각했습니다.

일전에[ lv2에서 찾아본 영한님의 관련 인프런 답글](https://www.inflearn.com/community/questions/288227/%EC%9D%B4%ED%95%B4%EC%95%88%EB%90%98%EB%8A%94%EB%B6%80%EB%B6%84%EC%9D%B4-%ED%9B%84%EB%B0%98%EB%B6%80%EC%97%90-%EB%82%98%EC%98%A4%EA%B2%A0%EC%A7%80%ED%96%88%EB%8A%94%EB%8D%B0-%EB%8B%B5%EC%9D%84-%EC%95%8C%EC%88%98%EC%97%86%EC%96%B4-%EC%A7%88%EB%AC%B8%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4%E3%85%9C)에서도 비슷한 맥락이 있엇던 것 같아 공유합니다. 

비토는 어떻게 생각하시나요? 합리적이지 않다고 생각한다면 이야기해주면 좋겠어요.

2024-12-29 21:21 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/fixture/FixtureGenerator.java
> +public class FixtureGenerator {
첫째로, 테스트 내에서 Dto나 의존관계를 위한 Fixture를 만들때 의미없는 dummy data로 인해 테스트가 잘 읽히지 않는 걸 선호하지 않는 편이에요.

둘째로, TextFixture의 경우 unsaved된 도메인 객체라는 점에서 SpringBootTest + Identity Id 생성전략을 사용하는 환경에서는 저장된 객체가 필요한 순간이 given절마다 생겨서 상수보다는 generator의 효용이 더 크게 와닿았던 것 같습니다.

2024-12-29 21:24 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/BaseServiceTest.java
> +    protected DtoGenerator dtoGenerator = new DtoGenerator();
1. 미안합니다. 앞으론 상의하고 도입할게유... 그런데 새벽 3시쯤 작업하는데 의견을 묻기가 그랬어요 ㅠㅠ
2. DtoGenerator는 인자값을 기반으로 ControllerTest를 위해 Dto를 생성하는 역할이고/ FixtureGenerator는 저장된 객체를 만들다보니 repository가 필요했어요. 따라서 bean 등록으로 의존성 주입이 필요했습니다.
3. 의도는 @TestConfiguration으로 테스트 환경에서만 generator가 등록되게 하기 위함인데, 스캔범위를 고려하면 크게 이유는 없는 것 같습니다.

2024-12-29 21:25 UTC, coli-geonwoo commented
/noti

1차적인 리뷰 반영과 답변 완료했습니다! 이제 2차전 가시죠! 

고독한 PR 골키퍼 올림..

2024-12-30 00:22 UTC, leegwichan requested changes
/noti @coli-geonwoo 
콜리 리뷰 반영하느라 고생 많았어~ 좀 더 고생해줘!

2024-12-30 00:22 UTC, leegwichan commented on src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
> +
DTO는 "형식이 올바른가?"를 검증하는 것이었고, Domain은 "도메인 규칙을 지켰는가?"를 검증해야 한다고 이야기 했던 것 같아요.

그런 관점에서 "time은 숫자의 형태를 지니고 있다"는 형식을 확인하는 것이고, "time은 양수로 쓰여야 한다"는 것은 도메인 규칙이라고 생각하는 데, 콜리는 이 의견에 동의하시나요?

2024-12-30 00:22 UTC, leegwichan commented on src/main/java/com/debatetimer/dto/parliamentary/response/ParliamentaryTableResponse.java
> +    }
가능하면 생성자를 쓰고, 큰 사유가 있을 때 정팩메를 쓰기로 했으니 지금 생성자를 쓴 건 좋은 것 같아요!

2024-12-30 00:22 UTC, leegwichan commented on src/test/java/com/debatetimer/BaseServiceTest.java
> +    protected DtoGenerator dtoGenerator = new DtoGenerator();
> DtoGenerator는 인자값을 기반으로 ControllerTest를 위해 Dto를 생성하는 역할이고/ FixtureGenerator는 저장된 객체를 만들다보니 repository가 필요했어요. 따라서 bean 등록으로 의존성 주입이 필요했습니다.

전부 의존성 주입으로 통일하는 건 어떻게 생각하세요?

> 의도는 @TestConfiguration으로 테스트 환경에서만 generator가 등록되게 하기 위함인데, 스캔범위를 고려하면 크게 이유는 없는 것 같습니다.

그러면... 그냥 `@Component`로 등록하는 건 어떨까요?

2024-12-30 00:22 UTC, leegwichan commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        return new ParliamentaryTableResponse(existingTable, savedTimeBoxes);
여기서 대화 이어갈게요~
저도 흐름에 따른 구분이라고 생각되었는데, 한 메서드에 3개는 지나치게 많다는 생각이 들었어요.
적어도 마지막 return 문은 공백 안넣어도 되지 않을까요? (저희 백엔드 컨벤션에 `return 하기 전 개행하지 않는다.`는 것이 있었습니다.)

2024-12-30 00:22 UTC, leegwichan commented on src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
> +                    .extract().as(ParliamentaryTableResponse.class);
https://github.com/debate-timer/debate-timer-be/pull/38#discussion_r1899186621
반영 했다며... 다른 테스트에도 반영 해줘야지...

2024-12-30 00:22 UTC, leegwichan commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +        void 의회식_토론_테이블을_생성_한다() {
[사소한 의견] ParliamentaryServiceTest의 테스트 메서드가 서술어 어간이랑 어미 사이에 띄어쓰기 되어있어요. 붙이는 건 어떨까요?

```suggestion
        @Test
        void 의회식_토론_테이블을_생성한다() {
```

2024-12-30 04:26 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/argumentresolver/AuthMemberArgumentResolver.java
> +            return memberRepository.getById(memberId);
확인해보니 Long.parseLong에서 null이 전달되서 바로 NumberFormatException이 발생하네요

2024-12-30 04:28 UTC, unifolio0 commented on src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
> +
저희 컨벤션 중에서 
> 입력에 대한 검증은 DTO에서, 비즈니스 정책에 대한 검증은 도메인에서 한다.

이런 컨벤션이 있는데 콜리가 말하는 간단한 validation이란 무엇을 의미하나요?

2024-12-30 04:31 UTC, unifolio0 commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +                .orElseThrow(() -> new DTClientErrorException(ClientErrorCode.MEMBER_TABLE_NOT_FOUND));
넵, 정확합니다.
> 이 과정이 반복되어야 하는데 CRUD 모든 코드에서 해당 검증이 코드상으로 필요했어요.

그래서 하나의 메소드로 분리한 것 아닌가요? 그러면 해당 메소드에서만 검증하고 다른 곳에서 이 메소드를 사용하면 될 것 같아요.

2024-12-30 04:32 UTC, unifolio0 commented on src/test/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxTest.java
> +                    .hasMessage("타임박스 유형과 일치하지 않는 입장입니다.");
그러면 괜찮을 것 같습니다

2024-12-30 04:38 UTC, unifolio0 commented on src/test/java/com/debatetimer/fixture/FixtureGenerator.java
> +public class FixtureGenerator {
저는 지금 방식이 더 잘 안 읽힌다고 생각하지만 크게 신경쓰는 부분은 아니라서 괜찮을 것 같네요.

2024-12-30 04:52 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
제 생각 전에 추가 질문 남길께요! 그러면 delete에서는 왜 void인가요? 삭제한 값의 결과를 활용하는 것은 update나 save와는 달리 클라이언트 측의 선택이 아니라고 생각한 이유가 궁금해요

2024-12-30 05:23 UTC, unifolio0 requested changes
/noti
이전 리뷰의 답글에 대한 답변과 추가 리뷰 남겼어요. 확인해주세요~

2024-12-30 05:23 UTC, unifolio0 commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +            ParliamentaryTableCreateRequest renewTableRequest =  dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
```suggestion
            ParliamentaryTableCreateRequest renewTableRequest = dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
```
이 부분을 복붙했는지 해당 코드를 사용하는 곳에서 전부 공백이 2개 들어가있네요.
[참고](https://velog.io/@pgmjun/IntelliJ-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC%EC%9D%84-%EC%84%A4%EC%A0%95%ED%95%B4%EB%B3%B4%EC%9E%90-feat.%EC%9A%B0%ED%85%8C%EC%BD%94)

이 글 보고 파일 저장할 때 자동 정렬 하도록 해놓으면 좋을 것 같아요. 이미 작성된 파일들은 직접 자동정렬(`option + command + L`)을 해주세요.

2024-12-30 05:23 UTC, unifolio0 commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +        void 회원_소유가_아닌_테이블_삭제_시_예외_발생() {
어떤 테스트명은 명사로 끝나고 어떤 테스트명은 동사로 끝나네요. 통일하는 건 어떨까요?

2024-12-30 05:23 UTC, unifolio0 commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +    ParliamentaryService parliamentaryService;
별 상관은 없지만 여기만 접근제어자를 지정 안 한 이유가 있을까요?

2024-12-30 05:51 UTC, leegwichan commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +            ParliamentaryTableCreateRequest renewTableRequest =  dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
`Ctrl + Alt + L` 입니다 ^^

2024-12-30 05:51 UTC, leegwichan commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +    ParliamentaryService parliamentaryService;
`private` 넣어 주세요

2024-12-30 17:31 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
> +
간단한 validation이라 칭한 것은 NotNull 검증처럼 도메인이나 비즈니스 로직에 한정되지 않고 자명하게 취급할 수 있는 제한조건을 통칭했습니다.

- 우선 DTO도 도메인에 대해서 일정 부분은 인지하고 있다고 생각했습니다. 
- 그 관점에서 time이 `발언시간` 이란 점을 알고 있다고 생각했습니다.
 - `발언시간은 양수이다`라는 명제는 발언시간이 -1분이다. 라는 표현이 어색한 것처럼 자명하다 생각했습니다. 
 - 따라서, DTO단에서의 검증도 가능하리라 생각했습니다.

비즈니스 규칙이라는 것은 우리 서비스에서만 규정하는 특별한 규칙이라 생각되는데 토론 도메인에서는 음수인 발언시간이 자명하게 가능하지 않다고 생각했습니다.

따라서 DTO단의 Positive로의 검증도 괜찮다고 생각했습니다.

2024-12-30 17:33 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
같은 관점에서 일관성을 지킨다면 delete된 행의 개수를 반환하는 정도는 괜찮다 생각해요.

다만 POST, PUT과 DELETE는 삭제를 시도하고, 그 삭제한 결과값을 이용할 일이 없다고 생각했습니다. 만약, 삭제를 시도하는 값을 이용해야 한다면 GET을 활용하면 된다고 생각해요.

2024-12-30 17:43 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/BaseServiceTest.java
> +    protected DtoGenerator dtoGenerator = new DtoGenerator();
1. 의존성 주입 통일 -> 필드 생성보다 일관성 있다는 점에서 괜찮다고 생각합니다. [반영 완료]
2. @Component로 모두 빈 등록해주었습니다~ [반영 완료]

2024-12-30 17:44 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/fixture/FixtureGenerator.java
> +public class FixtureGenerator {
나중에 가서는 generator로 인해 가독성이 더 안좋다고 느낄 부분이 있을 것 같은데, 목요일에 generator 관련해서 한번 회의해보시죠!

2024-12-30 18:03 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +                .orElseThrow(() -> new DTClientErrorException(ClientErrorCode.MEMBER_TABLE_NOT_FOUND));
**✅ 반영 완료**
에러 상황의 유일성이 보장되고 트래킹이 더 정확해진다는 점이 좋네요. 반영해주었습니다.

2024-12-30 18:06 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        return new ParliamentaryTableResponse(existingTable, savedTimeBoxes);
**✅ 반영 완료**

흐름에 대한 주관적인 부분이 있었기에 2가지 흐름으로 개행을 줄여주었습니다.

```java
    @Transactional
    public ParliamentaryTableResponse updateTable(
            ParliamentaryTableCreateRequest tableCreateRequest,
            long tableId,
            Member member
    ) {
        ParliamentaryTable existingTable = getOwnerTable(tableId, member.getId());
        ParliamentaryTable renewedTable = tableCreateRequest.toTable(member);
        existingTable.update(renewedTable);

        ParliamentaryTimeBoxes timeBoxes = timeBoxRepository.findTableTimeBoxes(existingTable);
        timeBoxRepository.deleteAllInBatch(timeBoxes.getTimeBoxes());
        ParliamentaryTimeBoxes savedTimeBoxes = saveTimeBoxes(tableCreateRequest, existingTable);
        return new ParliamentaryTableResponse(existingTable, savedTimeBoxes);
    }

```

2024-12-30 18:08 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerTest.java
> +                    .extract().as(ParliamentaryTableResponse.class);
반영해주었습니다... 🙇

2024-12-30 18:11 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +        void 의회식_토론_테이블을_생성_한다() {
✅ 모두 반영해주었습니다!

2024-12-30 18:13 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/domain/parliamentary/ParliamentaryTimeBoxes.java
> +    private static final Comparator<ParliamentaryTimeBox> TIME_BOX_COMPARATOR = Comparator.comparing(ParliamentaryTimeBox::getSequence);
**✅ 반영 완료**

반영해주었습니다~

```java
@Getter
public class ParliamentaryTimeBoxes {

    private static final Comparator<ParliamentaryTimeBox> TIME_BOX_COMPARATOR = Comparator
            .comparing(ParliamentaryTimeBox::getSequence);

    private final List<ParliamentaryTimeBox> timeBoxes;

    public ParliamentaryTimeBoxes(List<ParliamentaryTimeBox> timeBoxes) {
        timeBoxes.sort(TIME_BOX_COMPARATOR);
        this.timeBoxes = timeBoxes;
    }
}


```

2024-12-30 18:15 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/config/AuthMemberArgumentResolver.java
> +        }
✅ 반영 완료

반영해주었습니다! 일단, NFE도 같이 잡아주는 것으로 하고, 추후 AuthService로 대체할게요!

2024-12-30 18:26 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/argumentresolver/AuthMemberArgumentResolver.java
> +            return memberRepository.getById(memberId);
NFE도 우선 같이 잡아서 처리해주도록 했어요.
추후, AuthService로 대체하면서 NFE를 잡도록 한 코드를 제거해주면 될 것 같습니다.

2024-12-30 18:27 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +            ParliamentaryTableCreateRequest renewTableRequest =  dtoGenerator.generateParliamentaryTableCreateRequest("새로운 테이블");
설정되어있으나 자동정렬이 습관이 잘 안잡혀있는 것 같습니다 😭  유의하겠슴다ㅠㅠ

2024-12-30 18:28 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +        void 회원_소유가_아닌_테이블_삭제_시_예외_발생() {
✅ 반영 완료

동사로 통일해주었습니다.

2024-12-30 18:28 UTC, coli-geonwoo commented on src/test/java/com/debatetimer/service/parliamentary/ParliamentaryServiceTest.java
> +    ParliamentaryService parliamentaryService;
**✅ 반영 완료**

반영해주었습니다.

2024-12-30 18:31 UTC, coli-geonwoo commented
/noti

2차 리뷰 반영 완료했습니다

3차전 가시죠!! 🏃

2024-12-31 00:22 UTC, leegwichan commented on src/main/java/com/debatetimer/controller/exception/errorcode/ClientErrorCode.java
저는 좋습니다~

2024-12-31 00:23 UTC, leegwichan approved these changes
/noti
3차전은 귀찮으니까 추후 회의로 대체하겠습니다.
Approve 하겠습니다.

2024-12-31 04:15 UTC, unifolio0 commented on src/main/java/com/debatetimer/dto/parliamentary/request/TimeBoxCreateRequest.java
> +
콜리가 말하는게 어떤 건지는 이해했습니다! 크게 중요한 부분은 아니니 이것도 괜찮은 것 같네요

2024-12-31 04:20 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
1. 그렇다면 POST, PUT도 이용해야 하는 값을 GET을 통해 얻으면 되지 않나요? 
2. 삭제를 시도한 값을 GET을 통해 얻어온 뒤 DELETE의 실패여부에 따라 관련 정보를 사용할 지 여부를 프론트에서 결정하는 것보다 백에서 DELETE를 통해 삭제한 값을 반환해주는 게 더 리소스가 적지 않을까요? 
3. 삭제한 값을 알림과 같은 방식으로 알려주는 등 삭제한 결과값을 이용할 방법은 있는 것 같아요.

2024-12-31 04:44 UTC, unifolio0 requested changes
/noti
전 3차전 해야 될 것 같아요

2024-12-31 04:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/exception/errorcode/ClientErrorCode.java
> +    NOT_TABLE_OWNER(HttpStatus.BAD_REQUEST, "테이블을 소유한 회원이 아닙니다."),
왜 인증 인가와 관련된 Status가 아닌 Bad Request라고 생각하셨나요?

2024-12-31 04:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/exception/errorcode/ClientErrorCode.java
저도 좋아요

2024-12-31 04:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        ParliamentaryTable existingTable = getOwnerTable(tableId, member.getId());
[사소한 질문]
지금 `member.getId`에서 반환하는 값은 `Long`이고 `getOwnerTable`의 매개변수의 타입은 `long`인데 왜 자동 언박싱을 했나요?

2024-12-31 04:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
1. 그렇다면 POST, PUT도 이용해야 하는 값을 GET을 통해 얻으면 되지 않나요? 
2. 삭제를 시도한 값을 GET을 통해 얻어온 뒤 DELETE의 실패여부에 따라 관련 정보를 사용할 지 여부를 프론트에서 결정하는 것보다 백에서 DELETE를 통해 삭제한 값을 반환해주는 게 더 리소스가 적지 않을까요? 
3. 삭제한 값을 알림과 같은 방식으로 알려주는 등 삭제한 결과값을 이용할 방법은 있는 것 같아요.

2024-12-31 04:44 UTC, unifolio0 commented on src/test/java/com/debatetimer/domain/member/MemberTest.java
> +import com.debatetimer.domain.parliamentary.ParliamentaryTable;
이거 사용하는 import인가요?

2024-12-31 04:44 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerSwagger.java
> +import org.springframework.web.bind.annotation.PathVariable;
`Settings` -> `Editor` -> `General` -> `Auto Import` -> `Optimize imports on the fly` 체크

2024-12-31 17:23 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryControllerSwagger.java
> +import org.springframework.web.bind.annotation.PathVariable;
헉 이런 방법이 ... 감사합니다 🙇

2024-12-31 18:08 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/exception/errorcode/ClientErrorCode.java
**✅ 반영 완료**

최상위 패키지로 변경해주었습니다.

2024-12-31 18:12 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/exception/errorcode/ClientErrorCode.java
> +    NOT_TABLE_OWNER(HttpStatus.BAD_REQUEST, "테이블을 소유한 회원이 아닙니다."),
1.  TABLE_NOT_FOUND의 경우 repository에서 반환하는 예외입니다.
2. 테이블을 찾으려 했으나, 찾지 못했다는 것에는 ResourceNotFoundException처럼 NOT_FOUND가 적절하다고 생각했습니다.
3. 또한, 해당 메서드가 상위 인증 과정에서 쓰이는 것을 의식해서 ClientErrorCode를 정해주고 싶지 않았습니다.
4. 따라서 NOT_FOUND로 정해두고 AuthMemberArgumentResolver에서 인증과정에서 DTException을 잡아 401을 반환하도록 하였습니다.

2024-12-31 18:15 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        ParliamentaryTable existingTable = getOwnerTable(tableId, member.getId());
✅ 반영 완료

Repository에 null값을 받는 상황에 있어 fail fast를 준수함과 동시에 불필요한 쿼리가 날아가지 않도록 하려는 의도가 있습니다.

member의 경우 작업 범위가 제가 아니었어서 불일치가 있었던 것 같아요. primitive type으로 일치 시키겠습니다.

2024-12-31 18:28 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
> 1. 그렇다면 POST, PUT도 이용해야 하는 값을 GET을 통해 얻으면 되지 않나요?
- POST, PUT 처럼 갱신 요청 이후의 결과값을 활용하는 맥락보다 삭제 요청 이후의 삭제된 값을 활용하는 맥락이 적으리라 판단했습니다.

> 2. 삭제를 시도한 값을 GET을 통해 얻어온 뒤 DELETE의 실패여부에 따라 관련 정보를 사용할 지 여부를 프론트에서 결정하는 것보다 백에서 DELETE를 통해 삭제한 값을 반환해주는 게 더 리소스가 적지 않을까요?

- 삭제 api의 흐름이 대부분 삭제 시도 대상의 정보를 전달해준다는 점에서 삭제 대상에 대한 정보를 사전적으로 알아야 하지 않나요?
- 그 관점에서는 delete 전에 get요청이 필연적으로 따라와야 한다고 생각했어요. 다만 분기처리를 해야한다는 점 / 다른 api와 일관성이 없게 보일 수 있다는 점 등이 걸릴 수 있겠네요.

> 3. 삭제한 값을 알림과 같은 방식으로 알려주는 등 삭제한 결과값을 이용할 방법은 있는 것 같아요.

- 이미 tableId를 삭제 api에 보내준다는 것에서 테이블에 대한 정보를 가지고 있는 상태 아닌가요? 개인적으로 delete는 삭제에 대한 완료여부만을 알려주어도 괜찮다고 생각해요.

- 실제로 mozilla의 상태코드 204(NO_CONTENT)에 대한 설명을 보면, 본문이 없는 응답을 나타냄을 명시하고 있습니다.

> 이 상태코드는 본문 없는 응답을 위한 상태 코드이지만, 서버에서 잘못되게 본문을 포함한 응답을 전달하는 경우가 존재할 수 있습니다. 이 프로토콜은 사용자 에이전트 다양한 방법으로 처리하는 것을 허용하고 있습니다. [이 명세에 대한 토론은 여기서 확인할 수 있습니다.](https://github.com/httpwg/http-core/issues/26) 보통 지속 연결에서 볼 수 있는 문제로, 잘못 포함된 본문이 이후 요청에 대한 별도의 응답을 담고 있을 수 있습니다.

출처 : https://developer.mozilla.org/ko/docs/Web/HTTP/Status/204

2024-12-31 18:37 UTC, coli-geonwoo commented
/noti

3차 코드리뷰 반영했습니다~

4차전 가시죠 💪

2025-01-01 01:49 UTC, unifolio0 requested changes
아마 마지막 rc가 될 것 같네요.
/noti

2025-01-01 01:49 UTC, unifolio0 commented on src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
> +    NOT_TABLE_OWNER(HttpStatus.BAD_REQUEST, "테이블을 소유한 회원이 아닙니다."),
> TABLE_NOT_FOUND의 경우 repository에서 반환하는 예외입니다.
테이블을 찾으려 했으나, 찾지 못했다는 것에는 ResourceNotFoundException처럼 NOT_FOUND가 적절하다고 생각했습니다.
또한, 해당 메서드가 상위 인증 과정에서 쓰이는 것을 의식해서 ClientErrorCode를 정해주고 싶지 않았습니다.
따라서 NOT_FOUND로 정해두고 AuthMemberArgumentResolver에서 인증과정에서 DTException을 잡아 401을 반환하도록 하였습니다

저는 `NOT_TABLE_OWNER`를 말한 거였어요.

2025-01-01 01:49 UTC, unifolio0 commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        ParliamentaryTable existingTable = getOwnerTable(tableId, member.getId());
저는 member.getId의 반환값이 Long이고 다른 tableId 같은 것도 Long인데 중간에 long으로 바꾸는 이유가 궁금한 거였어요

2025-01-01 01:49 UTC, unifolio0 commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
사실 이미 콜리의 첫 답변 이후에 지금 같은 형태가 괜찮겠다 생각했는데 답변이 궁금해서 계속 추가질문 남겼습니다. 이대로 가면 좋을 것 같아요! 다만 답변들에 대해 제 생각을 좀 적어보자면...

> 이미 tableId를 삭제 api에 보내준다는 것에서 테이블에 대한 정보를 가지고 있는 상태 아닌가요? 개인적으로 delete는 삭제에 대한 완료여부만을 알려주어도 괜찮다고 생각해요.
실제로 mozilla의 상태코드 204(NO_CONTENT)에 대한 설명을 보면, 본문이 없는 응답을 나타냄을 명시하고 있습니다.

만약 프론트에서 삭제한 테이블의 이름을 활용해 `콜리 1 테이블이 삭제되었습니다` 같은 알림을 띄어줄거라 하면 tableId만으로 가능한 가요? delete에서 삭제된 정보를 보내줘야하지 않나요?
그리고 [rfc링크](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.5) 여기에서도 DELETE에서 응답 메시지를 반환할때 상태코드 `200`이 쓰일 수 있다고 나와있습니다.

> 프론트 로직에 의존적인 API 설계보다는 save와 update 이후의 결과값을 반환하는게 일반적인 API 설계라고 생각했기 때문이에요.
첫째로, 실제 API 동작 결과를 확인할 수 있다는 점에서 테스트에 용이한 메서드라 생각했고,
둘째로, update와 save의 결과를 활용하는 것은 클라이언트 측의 선택이라 생각했습니다.

제가 생각하는 것은 분산 시스템과도 관련이 있을 것 같아요. `POST, PUT 처럼 갱신 요청 이후의 결과값을 활용하는 맥락` 이렇게 콜리가 언급한 것처럼 POST, PUT 이후에 해당 결과를 활용할 때도 있을텐데 만약 분산 시스템이 적용된 상황에서 POST 이후 GET을 통해 해당 정보를 가져온다고 가정하면 만약 해당 분산 시스템이 강한 일관성을 가지지 않으면 잘못된 값을 반환하겠죠. 그래서 미래를 대비해 결과값을 반환하는 게 좋다고 봅니다.

2025-01-01 09:42 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/exception/errorcode/ClientErrorCode.java
> +    NOT_TABLE_OWNER(HttpStatus.BAD_REQUEST, "테이블을 소유한 회원이 아닙니다."),
✅ 반영 완료

오.. NOT_TABLE_OWNER는 api상 잘못된 파라미터를 넣어 요청했다는 측면에서 400이라 바라보았는데 접근권한이 없다는 메시지를 보면 401이 더 어울리네요. 합리적입니다. 반영해주었어요.

2025-01-01 09:44 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/service/parliamentary/ParliamentaryService.java
> +        ParliamentaryTable existingTable = getOwnerTable(tableId, member.getId());
- null값을 받아 엔티티를 찾는 과정은 도메인상에서 필요하지 않다고 생각했습니다.
- null 들어오는 경우 쿼리가 날아가는 것이 불필요하다 생각했습니다.

2025-01-01 09:59 UTC, coli-geonwoo commented on src/main/java/com/debatetimer/controller/parliamentary/ParliamentaryController.java
> +    public ParliamentaryTableResponse save(
비토와의 리뷰는 항상 재미있네요. 비토의 리뷰 하나하나마다 제가 간과한 부분들이나 꼼꼼함이 묻어나 제 생각이 넓어진다고 느껴요.

우선 결과값을 반환하는 것에 대한 제 생각을 정리하자면
- 결과값을 반환해야 하는가? 가 아니라 'Delete 요청에 결과값을 반환해야 하는가?' 에 조금 더 초점이 맞추어져 있어요.

그 관점에서 비토가 이야기한 replication lag을 고려한 측면에서 POST, PUT 등의 분산시스템에서 결과값 반환이 강한 장점을 가진다 생각합니다.

다만 Delete는 조금 굳이라는 생각이 든 것 같아요. 
먼저 status에 대해서는 delete api가 절대적으로 204를 반환해야한다고 주장하는 것은 아닙니다. 다만 api 명세서에서 합의한 상태코드가 204인만큼 204 + response body는 이상한 부분이 있다는 이야기를 하고 싶었어요. 만약 결과값을 반환해야 한다면 200과 함께 결과값을 반환해도 좋겠다고 생각해요.

그럼 결국 현재 도메인이나 확장성 측면에서 delete 시 결과값 반환이 합리적인가? 를 고민해야 하는데, 객체 삭제의 경우 결과값을 활용할 맥락이 크게 없다고 생각했어요.

비토는 그 반례로 id값이 아닌 다른 삭제된 객체의 다른 속성을 알아야 하는 상황을 들어주었는데요. 반대로 도메인에서 객체의 id를 알기 위해 객체의 단위를 조회한다면, 객체의 속성을 삭제 이후 반환하지 않아도 알고 있는 것이 아닐까, 하는 생각이 들어요. 즉 현재 도메인에 대입해 생각해보면 삭제 명령 시,  id를 아는데 table name을 모르는 상황이 잘 그려지지 않은 것 같아요.

이는 제가 이야기했던 가정이나 클라이언트를 고려한 api 설계라는 맥락으로 자충수가 될 수도 있는 이야기라 생각하는데요. 다만 JpaRepository의 구현을 보면 CRU의 경우 반환값이 있는데에 비해 Delete api는 모두 반환형이 void라는 점에서 합리적인 가정이 될 수 있다고 생각합니다.

2025-01-01 10:02 UTC, coli-geonwoo commented
/ noti

@unifolio0 4차 리뷰 반영했습니다~

5차전 가시죠 ~~🏃‍♂️

2025-01-01 10:13 UTC, unifolio0 commented
/noti
@coli-geonwoo 확인해보니 사용하지 않는 import를 지운게 커밋이 안 된 것 같아요. 한번 확인하고 다시 noti 주면 좋을 것 같아요!

2025-01-01 10:15 UTC, unifolio0 commented
/noti
추가로 한번 SonarLint를 돌린뒤에 리뷰 요청해주면 불필요한 리뷰가 줄어즐 것 같아요!

2025-01-01 10:40 UTC, unifolio0 approved these changes
/noti
이정도면 충분한 것 같아요. 이만 approve합니다. 수고하셨습니다~

2025-01-01 12:31 UTC, merged